# Set this website's info
# Change "coffeebank" to your GitHub username
# Change "moonrise" to your repository name
url: "https://www.salx.xyz"
baseurl: "/"
siteIcon: /media/android-chrome-192x192.png
siteYear: 2024
showinSearchEngines: true
# googleAnalyticsID: (uncomment to use)


# Set basic server info
serverName: 水岸兰香 v3.0
serverDescription: A Minecraft server where we have lots of fun!
serverIP: salx.xyz
useBedrockForOnlineStatus: false


# Discord information
kookInvite: https://www.kookapp.cn/app/invite/jgtFPP


# # Navbar Links at the top of the page (uncomment "siteNav" to use)
# #   name - The title on the navbar
# #   url - The link it should go to (for example, if you have "maps.md" file, put "maps")
# #   newtab - Whether link should open in new tab
# 
# siteNav:
#   - name: Server Map
#     url: map
#     newtab: true
#   - name: Screenshots
#     url: screenshots
#   - name: About
#     url: about


# Don't change anything below here, these are defaults set by GitHub Pages:
# ======
theme: minima
# plugins:
#   - jekyll-feed
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/